name: Final Project Eka

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      #download repository
      - uses: actions/checkout@v4

      #set up java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      #install/set up browser
      - name: Setup Browser
        uses: abhi1693/setup-browser@v0.3.5
        with:
          browser: chrome

      #set up gradle
      - name: Setup gradlew
        run: chmod +x gradlew

      #execute gradle comand for running cucumber test
      - name: Execute Test
        run: ./gradlew test
